-- Active: 1720829133941@@127.0.0.1@3306@kk
CREATE DATABASE interstellarinsight 
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
USE interstellarinsight;

create table TBL_CORPO_CELESTE(
ID_CorpoCeleste int primary key, 
nome varchar(100)
);
DESCRIBE TBL_CORPO_CELESTE;

create table TBL_PLANETAS(
ID_CorpoCeleste int primary key,
Distancia varchar(100),
Tamanho varchar(100), 
Composicao varchar(100),
atmosfera varchar(100),
foreign key(ID_CorpoCeleste) references TBL_CORPO_CELESTE(ID_CorpoCeleste)
);
DESCRIBE TBL_PLANETAS;

CREATE TABLE TBL_CARACTERISTICAS_GEOLOGICAS (
    ID_CorpoCeleste INT PRIMARY KEY,
    CaracteristicasGeologicas TEXT,
    FOREIGN KEY (ID_CorpoCeleste) REFERENCES TBL_CORPO_CELESTE(ID_CorpoCeleste)
);
DESCRIBE TBL_CARACTERISTICAS_GEOLOGICAS;

CREATE TABLE TBL_COMETAS (
    ID_CorpoCeleste INT PRIMARY KEY,
    Orbita VARCHAR(100),
    TipoDeComa VARCHAR(100),
    Posicao VARCHAR(100),
    FOREIGN KEY (ID_CorpoCeleste) REFERENCES TBL_CORPO_CELESTE(ID_CorpoCeleste)
);
DESCRIBE TBL_COMETAS;

CREATE TABLE TBL_ESTRELAS (
    EID_CorpoCeleste INT PRIMARY KEY,
    Distancia FLOAT,
    Sistema VARCHAR(100),
    Tamanho FLOAT,
    Composicao VARCHAR(100)
);
DESCRIBE TBL_ESTRELAS;

CREATE TABLE TBL_NEBULOSA(
    ID_CorpoCeleste INT PRIMARY KEY,
    Tipo VARCHAR(100),
    FOREIGN KEY (ID_CorpoCeleste) REFERENCES TBL_CORPO_CELESTE(ID_CorpoCeleste)
);
DESCRIBE TBL_NEBULOSA;

CREATE TABLE TBL_SONDAS (
    ID_Sonda INT PRIMARY KEY,
    Nome VARCHAR(100),
    Status VARCHAR(50)
);
DESCRIBE TBL_SONDAS;

CREATE TABLE TBL_HISTORICO_SONDAS (
    ID_Sonda INT,
    ID_Historico INT,
    PRIMARY KEY (ID_Sonda, ID_Historico),
    FOREIGN KEY (ID_Sonda) REFERENCES TBL_SONDAS(ID_Sonda)
);
DESCRIBE TBL_HISTORICO_SONDAS;

CREATE TABLE TBL_NAVES (
    ID_Nave INT PRIMARY KEY,
    Nome VARCHAR(100),
    Status VARCHAR(50)
);
DESCRIBE TBL_NAVES;

CREATE TABLE TBL_HISTORICO_NAVES (
    ID_Nave INT,
    ID_Historico INT,
    PRIMARY KEY (ID_Nave, ID_Historico),
    FOREIGN KEY (ID_Nave) REFERENCES TBL_NAVES(ID_Nave)
);
DESCRIBE TBL_HISTORICO_NAVES;

CREATE TABLE TBL_GALAXIAS (
    ID_Galaxia INT PRIMARY KEY,
    Nome VARCHAR(100)
);
DESCRIBE TBL_GALAXIAS;

CREATE TABLE TBL_HISTORICO_GALAXIAS (
    ID_Galaxia INT,
    ID_Historico INT,
    PRIMARY KEY (ID_Galaxia, ID_Historico),
    FOREIGN KEY (ID_Galaxia) REFERENCES TBL_GALAXIAS(ID_Galaxia)
);
DESCRIBE TBL_HISTORICO_GALAXIAS;

CREATE TABLE TBL_MISSOES_TRIPULADAS (
    NomeMissao VARCHAR(100) PRIMARY KEY,
    DataDeLancamento DATE,
    DuracaoEstipulada VARCHAR(50),
    Objetivos TEXT
);
DESCRIBE TBL_MISSOES_TRIPULADAS;

CREATE TABLE TBL_NOMEMISSAO_NAVE (
    NomeMissao VARCHAR(100),
    ID_Nave INT,
    PRIMARY KEY (NomeMissao, ID_Nave),
    FOREIGN KEY (NomeMissao) REFERENCES TBL_MISSOES_TRIPULADAS(NomeMissao),
    FOREIGN KEY (ID_Nave) REFERENCES TBL_NAVES(ID_Nave)
);
DESCRIBE TBL_NOMEMISSAO_NAVE;

CREATE TABLE TBL_MISSOES_NAO_TRIPULADAS (
    NomeMissao VARCHAR(100) PRIMARY KEY,
    DataDeLancamento DATE,
    Duracao VARCHAR(50),
    Objetivos TEXT
);
DESCRIBE TBL_MISSOES_NAO_TRIPULADAS;

CREATE TABLE TBL_ENVOLVIDOS (
    ID_Sonda INT PRIMARY KEY,
    NomeSonda VARCHAR(100)
);
DESCRIBE TBL_ENVOLVIDOS; 

CREATE TABLE TBL_TRIPULACAO (
    ID_Tripulacao INT PRIMARY KEY,
    NomeMissao VARCHAR(100),
    FOREIGN KEY (NomeMissao) REFERENCES TBL_MISSOES_TRIPULADAS(NomeMissao)
);
DESCRIBE TBL_TRIPULACAO;

CREATE TABLE TBL_FUNCIONARIOS_TRIPULACAO (
    ID_Tripulacao INT,
    ID_Funcionario INT,
    PRIMARY KEY (ID_Tripulacao, ID_Funcionario),
    FOREIGN KEY (ID_Tripulacao) REFERENCES TBL_TRIPULACAO(ID_Tripulacao)
);
DESCRIBE TBL_FUNCIONARIOS_TRIPULACAO;

CREATE TABLE TBL_FUNCIONARIOS (
    ID_Funcionario INT PRIMARY KEY,
    Status VARCHAR(50)
);
DESCRIBE TBL_FUNCIONARIOS;

CREATE TABLE TBL_CIENTISTAS (
    ID_Funcionario INT PRIMARY KEY,
    AreaDePesquisa VARCHAR(100),
    Especializacao INT,
    FOREIGN KEY (ID_Funcionario) REFERENCES TBL_FUNCIONARIOS(ID_Funcionario)
);
DESCRIBE TBL_CIENTISTAS;

CREATE TABLE TABELA_ESPECIALIZACAO_CIENTISTA (
    ID_especializacao INT PRIMARY KEY,
    Especializacao VARCHAR(100)
);
DESCRIBE TABELA_ESPECIALIZACAO_CIENTISTA;

CREATE TABLE TBL_ENGENHEIRO (
    ID_Funcionario INT PRIMARY KEY,
    Especializacao INT,
    FOREIGN KEY (ID_Funcionario) REFERENCES TBL_FUNCIONARIOS(ID_Funcionario)
);
DESCRIBE TBL_ENGENHEIRO;

CREATE TABLE TABELA_ESPECIALIZACAO_ENGENHEIRO (
    ID_especializacao INT PRIMARY KEY,
    Especializacao VARCHAR(100)
);
DESCRIBE TABELA_ESPECIALIZACAO_ENGENHEIRO;

CREATE TABLE TABELA_TIPO_FUNCIONARIOS (
    ID_Funcionario INT,
    TipoFuncionario VARCHAR(100),
    PRIMARY KEY (ID_Funcionario),
    FOREIGN KEY (ID_Funcionario) REFERENCES TBL_FUNCIONARIOS(ID_Funcionario)
);
DESCRIBE TABELA_TIPO_FUNCIONARIOS;

CREATE TABLE TABELA_HISTORICO_MISSOES_FUNCIONARIO (
    ID_Historico INT PRIMARY KEY,
    ID_Funcionario INT,
    FOREIGN KEY (ID_Funcionario) REFERENCES TBL_FUNCIONARIOS(ID_Funcionario)
);
DESCRIBE TABELA_HISTORICO_MISSOES_FUNCIONARIO;

CREATE TABLE TABELA_HISTORICO_MISSOES_NOMEMISSAO (
    ID_Historico INT PRIMARY KEY,
    NomeMissao VARCHAR(100),
    FOREIGN KEY (NomeMissao) REFERENCES TBL_MISSOES_TRIPULADAS(NomeMissao)
);
DESCRIBE TABELA_HISTORICO_MISSOES_NOMEMISSAO ;

CREATE TABLE TABELA_ID_SETOR (
    ID_SETOR INT PRIMARY KEY,
    Setor VARCHAR(100)
);
DESCRIBE TABELA_ID_SETOR;

CREATE TABLE TABELA_ADM (
    ID_Funcionario INT PRIMARY KEY,
    Nome VARCHAR(100),
    Sobrenome VARCHAR(100),
    FOREIGN KEY (ID_Funcionario) REFERENCES TBL_FUNCIONARIOS(ID_Funcionario)
);
DESCRIBE TABELA_ID_SETOR; 

CREATE TABLE TABELA_FUNCIONARIO_SETOR (
    ID_Funcionario INT,
    ID_SETOR INT,
    PRIMARY KEY (ID_Funcionario),
    FOREIGN KEY (ID_Funcionario) REFERENCES TBL_FUNCIONARIOS(ID_Funcionario),
    FOREIGN KEY (ID_SETOR) REFERENCES TABELA_ID_SETOR(ID_SETOR)
);
DESCRIBE TABELA_FUNCIONARIO_SETOR;

CREATE TABLE TABELA_RH (
    ID_Funcionario INT PRIMARY KEY,
    ID_SETOR INT,
    FOREIGN KEY (ID_Funcionario) REFERENCES TBL_FUNCIONARIOS(ID_Funcionario),
    FOREIGN KEY (ID_SETOR) REFERENCES TABELA_ID_SETOR(ID_SETOR)
);
DESCRIBE TABELA_RH;

CREATE TABLE TABELA_DADOS_FINANCEIROS (
    NomeMissao VARCHAR(100),
    Orcamento DECIMAL(10, 2),
    Gastos DECIMAL(10, 2),
    Receitas DECIMAL(10, 2),
    BalancoFinanceiro DECIMAL(10, 2),
    FOREIGN KEY (NomeMissao) REFERENCES TBL_MISSOES_TRIPULADAS(NomeMissao)
);
DESCRIBE TABELA_DADOS_FINANCEIROS;

CREATE TABLE TABELA_DADOS_CIENTIFICOS (
    NomeMissao VARCHAR(100),
    DataDeLancamento DATE,
    Conteudo TEXT,
    FOREIGN KEY (NomeMissao) REFERENCES TBL_MISSOES_TRIPULADAS(NomeMissao)
);
DESCRIBE TABELA_DADOS_CIENTIFICOS;


